//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lps_domotica_vista.IWSEnergia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/domotica_WcfService.Energia")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> AnexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Anexo {
            get {
                return this.AnexoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnexoField, value) != true)) {
                    this.AnexoField = value;
                    this.RaisePropertyChanged("Anexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWSEnergia.IWSEnergia")]
    public interface IWSEnergia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEnergia/AgregarEnergia", ReplyAction="http://tempuri.org/IWSEnergia/AgregarEnergiaResponse")]
        lps_domotica_vista.IWSEnergia.Respuesta AgregarEnergia(string pId, System.DateTime pFechaHora, int pHora, double pPotencia, int pDispositivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSEnergia/AgregarEnergia", ReplyAction="http://tempuri.org/IWSEnergia/AgregarEnergiaResponse")]
        System.Threading.Tasks.Task<lps_domotica_vista.IWSEnergia.Respuesta> AgregarEnergiaAsync(string pId, System.DateTime pFechaHora, int pHora, double pPotencia, int pDispositivo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSEnergiaChannel : lps_domotica_vista.IWSEnergia.IWSEnergia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSEnergiaClient : System.ServiceModel.ClientBase<lps_domotica_vista.IWSEnergia.IWSEnergia>, lps_domotica_vista.IWSEnergia.IWSEnergia {
        
        public WSEnergiaClient() {
        }
        
        public WSEnergiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSEnergiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEnergiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSEnergiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public lps_domotica_vista.IWSEnergia.Respuesta AgregarEnergia(string pId, System.DateTime pFechaHora, int pHora, double pPotencia, int pDispositivo) {
            return base.Channel.AgregarEnergia(pId, pFechaHora, pHora, pPotencia, pDispositivo);
        }
        
        public System.Threading.Tasks.Task<lps_domotica_vista.IWSEnergia.Respuesta> AgregarEnergiaAsync(string pId, System.DateTime pFechaHora, int pHora, double pPotencia, int pDispositivo) {
            return base.Channel.AgregarEnergiaAsync(pId, pFechaHora, pHora, pPotencia, pDispositivo);
        }
    }
}
