//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lps_domotica_vista.IWSAdministracion {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dispositivo", Namespace="http://schemas.datacontract.org/2004/07/domotica_admin.Modelo")]
    [System.SerializableAttribute()]
    public partial class Dispositivo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lps_domotica_vista.IWSAdministracion.EEstadoDispositivo EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdDispositivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private lps_domotica_vista.IWSAdministracion.ETipoDispositivo TipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lps_domotica_vista.IWSAdministracion.EEstadoDispositivo Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDispositivo {
            get {
                return this.IdDispositivoField;
            }
            set {
                if ((object.ReferenceEquals(this.IdDispositivoField, value) != true)) {
                    this.IdDispositivoField = value;
                    this.RaisePropertyChanged("IdDispositivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.IdUsuarioField, value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public lps_domotica_vista.IWSAdministracion.ETipoDispositivo Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EEstadoDispositivo", Namespace="http://schemas.datacontract.org/2004/07/domotica_admin.Modelo")]
    public enum EEstadoDispositivo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ACTIVO = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INACTIVO = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETipoDispositivo", Namespace="http://schemas.datacontract.org/2004/07/domotica_admin.Modelo")]
    public enum ETipoDispositivo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ENERGIA = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEGURIDAD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILUMINACION = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ETipoAlarma", Namespace="http://schemas.datacontract.org/2004/07/domotica_admin.Modelo")]
    public enum ETipoAlarma : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISPOSTIVO_VALOR_DOUBLE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DISPOSTIVO_VALOR_FECHA = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/domotica_WcfService.Administracion")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> AnexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Anexo {
            get {
                return this.AnexoField;
            }
            set {
                if ((object.ReferenceEquals(this.AnexoField, value) != true)) {
                    this.AnexoField = value;
                    this.RaisePropertyChanged("Anexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IWSAdministracion.IWSAdministracion")]
    public interface IWSAdministracion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAdministracion/AgregarAlarma", ReplyAction="http://tempuri.org/IWSAdministracion/AgregarAlarmaResponse")]
        lps_domotica_vista.IWSAdministracion.Respuesta AgregarAlarma(string pIdAlarma, string pNombre, System.DateTime pFechaHora, lps_domotica_vista.IWSAdministracion.Dispositivo pDispositivo, double pLimite_Inferior, double pLimite_Superior, lps_domotica_vista.IWSAdministracion.ETipoAlarma pTipificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAdministracion/AgregarAlarma", ReplyAction="http://tempuri.org/IWSAdministracion/AgregarAlarmaResponse")]
        System.Threading.Tasks.Task<lps_domotica_vista.IWSAdministracion.Respuesta> AgregarAlarmaAsync(string pIdAlarma, string pNombre, System.DateTime pFechaHora, lps_domotica_vista.IWSAdministracion.Dispositivo pDispositivo, double pLimite_Inferior, double pLimite_Superior, lps_domotica_vista.IWSAdministracion.ETipoAlarma pTipificacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAdministracion/ListarAlarma", ReplyAction="http://tempuri.org/IWSAdministracion/ListarAlarmaResponse")]
        lps_domotica_vista.IWSAdministracion.Respuesta ListarAlarma();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSAdministracion/ListarAlarma", ReplyAction="http://tempuri.org/IWSAdministracion/ListarAlarmaResponse")]
        System.Threading.Tasks.Task<lps_domotica_vista.IWSAdministracion.Respuesta> ListarAlarmaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSAdministracionChannel : lps_domotica_vista.IWSAdministracion.IWSAdministracion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAdministracionClient : System.ServiceModel.ClientBase<lps_domotica_vista.IWSAdministracion.IWSAdministracion>, lps_domotica_vista.IWSAdministracion.IWSAdministracion {
        
        public WSAdministracionClient() {
        }
        
        public WSAdministracionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAdministracionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAdministracionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAdministracionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public lps_domotica_vista.IWSAdministracion.Respuesta AgregarAlarma(string pIdAlarma, string pNombre, System.DateTime pFechaHora, lps_domotica_vista.IWSAdministracion.Dispositivo pDispositivo, double pLimite_Inferior, double pLimite_Superior, lps_domotica_vista.IWSAdministracion.ETipoAlarma pTipificacion) {
            return base.Channel.AgregarAlarma(pIdAlarma, pNombre, pFechaHora, pDispositivo, pLimite_Inferior, pLimite_Superior, pTipificacion);
        }
        
        public System.Threading.Tasks.Task<lps_domotica_vista.IWSAdministracion.Respuesta> AgregarAlarmaAsync(string pIdAlarma, string pNombre, System.DateTime pFechaHora, lps_domotica_vista.IWSAdministracion.Dispositivo pDispositivo, double pLimite_Inferior, double pLimite_Superior, lps_domotica_vista.IWSAdministracion.ETipoAlarma pTipificacion) {
            return base.Channel.AgregarAlarmaAsync(pIdAlarma, pNombre, pFechaHora, pDispositivo, pLimite_Inferior, pLimite_Superior, pTipificacion);
        }
        
        public lps_domotica_vista.IWSAdministracion.Respuesta ListarAlarma() {
            return base.Channel.ListarAlarma();
        }
        
        public System.Threading.Tasks.Task<lps_domotica_vista.IWSAdministracion.Respuesta> ListarAlarmaAsync() {
            return base.Channel.ListarAlarmaAsync();
        }
    }
}
